PORT: 8002
DB_HOST: localhost
DB_PORT: 5432
DB_USERNAME: admin
DB_PASSWORD: 1234
DB_NAME: auth-service
JWT_SECRET_KEY: 2390129ejd1e90ueu10e129eSDFDdDDiSDFsFDDfh0OIHOISDHdfsSDHFOIh
JWT_EXP_TIME: 300000

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${PORT}