version: "3.8"
services:
  db:
    image: postgres
    container_name: pgdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./docker-valumes/pgdb:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gamil.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - ./docker-valumes/pgadmin:/pgadmin-data:/var/lib/pgadmin


